#
# Devhub Website
# GitHub Actions
# GitHub Pages Deployment workflow
#

name: Build & Deploy to GitHub Pages
on: push
jobs:
  build:
    # permissions to clone the repo and create a page deployment
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build & Upload Site as Artifact
        uses: withastro/action@v3
        with:
          path: frontend # The root location of your Astro project inside the repository. (optional)
          node-version: 20 # The specific version of Node that should be used to build your site. Defaults to 20. (optional)
          package-manager: npm@latest
      - name: Deploy to GitHub Pages
        # only deploy on main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        id: deployment
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
